In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchviz import make_dot
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from tqdm import tqdm

### Embedding Layer

In [9]:
emb = nn.Embedding(5,4)
emb.weight

Parameter containing:
tensor([[ 1.2823, -0.1933,  1.0879,  0.1986],
        [ 0.4589, -0.2700, -0.8669,  0.2112],
        [-1.7392, -1.6151, -0.3644, -0.8449],
        [-0.2848, -1.4877, -0.1491, -0.8627],
        [-0.6281, -0.1523, -1.3398,  1.0341]], requires_grad=True)

Embedding layers are like lookup tables. You can retrive vectors by indexing.

In [10]:
idx = torch.tensor([0])
emb(idx)

tensor([[ 1.2823, -0.1933,  1.0879,  0.1986]], grad_fn=<EmbeddingBackward0>)

In [11]:
idx = torch.tensor([0,2])
emb(idx)

tensor([[ 1.2823, -0.1933,  1.0879,  0.1986],
        [-1.7392, -1.6151, -0.3644, -0.8449]], grad_fn=<EmbeddingBackward0>)